# Site settings
title: Arificial Intelligence
subtitle: Arificial Intelligence by the University of Zanjan
description: |
    This course is about the theory and practice of Artificial Intelligence. 
    We will study modern techniques for computers to represent task-relevant information and make intelligent (i.e., satisficing or optimal) decisions towards the achievement of goals.
    The search and problem-solving methods are applicable throughout a large range of industrial, civil, medical, financial, robotic, and information systems.
    We will investigate questions about AI systems such as: how to represent knowledge, how to effectively generate appropriate sequences of actions and how to search among alternatives to find optimal or near-optimal solutions.
    We will also explore how to deal with uncertainty in the world and how to learn from experience.
    We will cover the aggregation of conflicting preferences and computational game theory.
    Throughout the course, we will discuss topics such as AI and Ethics and introduce applications related to AI for Social Good.
    We expect that by the end of the course students will have a thorough understanding of the algorithmic foundations of AI, how probability and AI are closely interrelated, 
    and how automated agents make decisions. We also expect students to acquire a strong appreciation of the big-picture aspects of developing fully autonomous intelligent agents.
baseurl: "https://rahmanidashti.github.io/" # the subpath of your site, e.g. /blog/
url: "https://rahmanidashti.github.io/znuai/" # the base hostname & protocol for your site
syllabus: "https://github.com/svmiller/svm-r-markdown-templates/blob/master/svm-rmarkdown-syllabus-example.pdf"
githubdir: "rahmanidashti/znuai"

# Author/user information
email: srahmani@znu.ac.ir
twitter_username: stevenvmiller
github_username:  svmiller
authorurl: "http://maslab.znu.ac.ir"
address: |
    Department of Computer Engineering
    University of Zanjan
    Zanjan, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['/_images', '/_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
